-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Reflections"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100 CACHE 1 ),
    success character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "UserId" integer NOT NULL,
    "createdAt" date DEFAULT now(),
    "updatedAt" date DEFAULT now(),
    low_point character varying(100) COLLATE pg_catalog."default",
    take_away character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "Reflections_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100 CACHE 1 ),
    email character varying(200) COLLATE pg_catalog."default" NOT NULL,
    password character varying(225) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Users_pkey" PRIMARY KEY (id),
    CONSTRAINT "Users_email_key" UNIQUE (email)
);

ALTER TABLE IF EXISTS public."Reflections"
    ADD CONSTRAINT "UserId" FOREIGN KEY ("UserId")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;